name: Build Android APK

on:
  push:
    branches:
      - weight-slider
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-version: 33
          packages: |
            build-tools;33.0.2
            platforms;android-33
            platforms;android-30
            build-tools;30.0.3
            emulator;system-images;android-30;google_apis;x86
            extras;google;google_play_services
            extras;google;instantapps
            patcher;v4
            tools
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
          
      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}
          key: android-sdk-${{ hashFiles('**/build.gradle*') }}
          
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        
      - name: Build Release APK (带签名)
        if: ${{ secrets.ANDROID_SIGNING_KEY != '' }}
        run: |
          ./gradlew assembleRelease
          ls -laF app/build/outputs/apk/release/
